"""drop_unused_tables

Revision ID: 09988ed7ed19
Revises: c5c8c61b40d9
Create Date: 2026-01-09 01:05:52.494972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09988ed7ed19'
down_revision: Union[str, Sequence[str], None] = 'c5c8c61b40d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_pending_actions')
    op.drop_index(op.f('ix_telegram_chat_memory_chat_id'), table_name='telegram_chat_memory')
    op.drop_table('telegram_chat_memory')
    op.drop_index(op.f('ix_telegram_chat_states_off_topic_mode'), table_name='telegram_chat_states')
    op.drop_table('telegram_chat_states')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chat_states',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('off_topic_mode', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('off_topic_since', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_chat_states')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_chat_states_chat_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_telegram_chat_states_off_topic_mode'), 'telegram_chat_states', ['off_topic_mode'], unique=False)
    op.create_table('telegram_chat_memory',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_chat_memory')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_chat_memory_chat_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_telegram_chat_memory_chat_id'), 'telegram_chat_memory', ['chat_id'], unique=False)
    op.create_table('db_pending_actions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_db_pending_actions_session_id_telegram_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_db_pending_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_pending_actions'))
    )
    # ### end Alembic commands ###
