"""initial_schema_phase_1

Revision ID: 0abc3a5619c7
Revises: 
Create Date: 2026-02-17 21:56:06.449305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abc3a5619c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # Extensions required for search capabilities
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")   # trigram similarity search
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")     # pgvector for embeddings

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_lower', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index('idx_suppliers_name_lower', 'suppliers', ['name_lower'], unique=False)
    op.create_table('telegram_sessions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'processing', 'closed', name='telegram_session_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_sessions'))
    )
    op.create_index('ix_telegram_sessions_chat_id_status', 'telegram_sessions', ['chat_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_users_chat_id')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('llm_calls',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('openrouter_generation_id', sa.String(), nullable=True),
    sa.Column('upstream_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('cache_discount_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('upstream_inference_cost_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('cost_backfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openrouter_generation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_llm_calls_session_id_telegram_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls')),
    sa.UniqueConstraint('openrouter_generation_id', name=op.f('uq_llm_calls_openrouter_generation_id'))
    )
    op.create_index('ix_llm_calls_chat_id_requested_at', 'llm_calls', ['chat_id', 'requested_at'], unique=False)
    op.create_index('ix_llm_calls_purpose_requested_at', 'llm_calls', ['purpose', 'requested_at'], unique=False)
    op.create_index('ix_llm_calls_session_id_requested_at', 'llm_calls', ['session_id', 'requested_at'], unique=False)
    op.create_table('restaurants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('restaurant_code', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_restaurants_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants')),
    sa.UniqueConstraint('restaurant_code', name=op.f('uq_restaurants_restaurant_code'))
    )
    op.create_table('telegram_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('file_unique_id', sa.String(), nullable=True),
    sa.Column('file_kind', sa.String(), nullable=True),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_telegram_messages_session_id_telegram_sessions')),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('fk_telegram_messages_telegram_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_messages')),
    sa.UniqueConstraint('update_id', name=op.f('uq_telegram_messages_update_id'))
    )
    op.create_index('ix_telegram_messages_chat_id_received_at', 'telegram_messages', ['chat_id', 'received_at'], unique=False)
    op.create_index('ix_telegram_messages_file_unique_id', 'telegram_messages', ['file_unique_id'], unique=False)
    op.create_index('ix_telegram_messages_session_id', 'telegram_messages', ['session_id'], unique=False)
    op.create_table('file_processing_staging',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_unique_id', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'pending_review', 'confirmed', 'cancelled', 'error', name='staging_status'), server_default='processing', nullable=False),
    sa.Column('extracted_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_file_processing_staging_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_file_processing_staging_session_id_telegram_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_file_processing_staging_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_file_processing_staging_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_staging'))
    )
    op.create_index('idx_staging_restaurant_status', 'file_processing_staging', ['restaurant_id', 'status'], unique=False)
    op.create_index('idx_staging_uploaded_by', 'file_processing_staging', ['uploaded_by'], unique=False)
    op.create_table('restaurant_suppliers',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_restaurant_suppliers_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_suppliers_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_restaurant_suppliers_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_suppliers')),
    sa.UniqueConstraint('restaurant_id', 'supplier_id', name='uq_restaurant_suppliers_restaurant_supplier')
    )
    op.create_index('idx_restaurant_suppliers_restaurant', 'restaurant_suppliers', ['restaurant_id', 'is_active'], unique=False)
    op.create_table('restaurant_users',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_users_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_restaurant_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_users')),
    sa.UniqueConstraint('restaurant_id', 'user_id', name='uq_restaurant_users_member')
    )
    op.create_table('supplier_price_lists',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_supplier_price_lists_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_price_lists_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_price_lists'))
    )
    op.create_index('idx_price_lists_restaurant_supplier', 'supplier_price_lists', ['restaurant_id', 'supplier_id'], unique=False)
    op.create_table('telegram_outgoing_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], name=op.f('fk_telegram_outgoing_messages_llm_call_id_llm_calls')),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_telegram_outgoing_messages_session_id_telegram_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_outgoing_messages'))
    )
    op.create_index('ix_telegram_outgoing_messages_chat_id_sent_at', 'telegram_outgoing_messages', ['chat_id', 'sent_at'], unique=False)
    op.create_index('ix_telegram_outgoing_messages_kind_sent_at', 'telegram_outgoing_messages', ['kind', 'sent_at'], unique=False)
    op.create_index('ix_telegram_outgoing_messages_session_id_sent_at', 'telegram_outgoing_messages', ['session_id', 'sent_at'], unique=False)
    op.create_table('handshake_requests',
    sa.Column('staging_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['staging_id'], ['file_processing_staging.id'], name=op.f('fk_handshake_requests_staging_id_file_processing_staging'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_handshake_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handshake_requests'))
    )
    op.create_index('idx_handshake_staging', 'handshake_requests', ['staging_id', 'resolved_at'], unique=False)
    op.create_index('idx_handshake_user', 'handshake_requests', ['user_id', 'resolved_at'], unique=False)
    op.create_table('supplier_prices',
    sa.Column('price_list_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_name_lower', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_qty_minor', sa.BigInteger(), nullable=True),
    sa.Column('unit_qty_exp', sa.SmallInteger(), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('price_exp', sa.SmallInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['supplier_price_lists.id'], name=op.f('fk_supplier_prices_price_list_id_supplier_price_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_prices_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_prices'))
    )
    op.create_index('idx_supplier_prices_list', 'supplier_prices', ['price_list_id'], unique=False)
    op.create_index('idx_supplier_prices_supplier', 'supplier_prices', ['supplier_id', 'item_name_lower'], unique=False)

    # GIN trigram indexes (require pg_trgm extension above)
    op.execute("CREATE INDEX idx_suppliers_name_trgm ON suppliers USING GIN(name_lower gin_trgm_ops)")
    op.execute("CREATE INDEX idx_supplier_prices_name_trgm ON supplier_prices USING GIN(item_name_lower gin_trgm_ops)")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_supplier_prices_supplier', table_name='supplier_prices')
    op.drop_index('idx_supplier_prices_list', table_name='supplier_prices')
    op.drop_table('supplier_prices')
    op.drop_index('idx_handshake_user', table_name='handshake_requests')
    op.drop_index('idx_handshake_staging', table_name='handshake_requests')
    op.drop_table('handshake_requests')
    op.drop_index('ix_telegram_outgoing_messages_session_id_sent_at', table_name='telegram_outgoing_messages')
    op.drop_index('ix_telegram_outgoing_messages_kind_sent_at', table_name='telegram_outgoing_messages')
    op.drop_index('ix_telegram_outgoing_messages_chat_id_sent_at', table_name='telegram_outgoing_messages')
    op.drop_table('telegram_outgoing_messages')
    op.drop_index('idx_price_lists_restaurant_supplier', table_name='supplier_price_lists')
    op.drop_table('supplier_price_lists')
    op.drop_table('restaurant_users')
    op.drop_index('idx_restaurant_suppliers_restaurant', table_name='restaurant_suppliers')
    op.drop_table('restaurant_suppliers')
    op.drop_index('idx_staging_uploaded_by', table_name='file_processing_staging')
    op.drop_index('idx_staging_restaurant_status', table_name='file_processing_staging')
    op.drop_table('file_processing_staging')
    op.drop_index('ix_telegram_messages_session_id', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_file_unique_id', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_chat_id_received_at', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_table('restaurants')
    op.drop_index('ix_llm_calls_session_id_requested_at', table_name='llm_calls')
    op.drop_index('ix_llm_calls_purpose_requested_at', table_name='llm_calls')
    op.drop_index('ix_llm_calls_chat_id_requested_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('users')
    op.drop_index('ix_telegram_sessions_chat_id_status', table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    op.drop_index('idx_supplier_prices_name_trgm', table_name='supplier_prices')
    op.drop_index('idx_suppliers_name_trgm', table_name='suppliers')
    op.drop_index('idx_suppliers_name_lower', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
