"""add llm_calls + telegram_outgoing_messages + telegram_chat_states

Revision ID: 12f06baf426e
Revises: 75dd3a76161c
Create Date: 2026-01-02 12:28:32.385463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12f06baf426e'
down_revision: Union[str, Sequence[str], None] = '75dd3a76161c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chat_states',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('off_topic_mode', sa.Boolean(), nullable=False),
    sa.Column('off_topic_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_chat_states')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_chat_states_chat_id'))
    )
    op.create_index('ix_telegram_chat_states_off_topic_mode', 'telegram_chat_states', ['off_topic_mode'], unique=False)
    op.create_table('llm_calls',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('openrouter_generation_id', sa.String(), nullable=True),
    sa.Column('upstream_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('cache_discount_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('upstream_inference_cost_usd', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('cost_backfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openrouter_generation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_llm_calls_session_id_telegram_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls')),
    sa.UniqueConstraint('openrouter_generation_id', name=op.f('uq_llm_calls_openrouter_generation_id'))
    )
    op.create_index('ix_llm_calls_chat_id_requested_at', 'llm_calls', ['chat_id', 'requested_at'], unique=False)
    op.create_index('ix_llm_calls_purpose_requested_at', 'llm_calls', ['purpose', 'requested_at'], unique=False)
    op.create_index('ix_llm_calls_session_id_requested_at', 'llm_calls', ['session_id', 'requested_at'], unique=False)
    op.create_table('telegram_outgoing_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], name=op.f('fk_telegram_outgoing_messages_llm_call_id_llm_calls')),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_telegram_outgoing_messages_session_id_telegram_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_outgoing_messages'))
    )
    op.create_index('ix_telegram_outgoing_messages_chat_id_sent_at', 'telegram_outgoing_messages', ['chat_id', 'sent_at'], unique=False)
    op.create_index('ix_telegram_outgoing_messages_kind_sent_at', 'telegram_outgoing_messages', ['kind', 'sent_at'], unique=False)
    op.create_index('ix_telegram_outgoing_messages_session_id_sent_at', 'telegram_outgoing_messages', ['session_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_outgoing_messages_session_id_sent_at', table_name='telegram_outgoing_messages')
    op.drop_index('ix_telegram_outgoing_messages_kind_sent_at', table_name='telegram_outgoing_messages')
    op.drop_index('ix_telegram_outgoing_messages_chat_id_sent_at', table_name='telegram_outgoing_messages')
    op.drop_table('telegram_outgoing_messages')
    op.drop_index('ix_llm_calls_session_id_requested_at', table_name='llm_calls')
    op.drop_index('ix_llm_calls_purpose_requested_at', table_name='llm_calls')
    op.drop_index('ix_llm_calls_chat_id_requested_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_telegram_chat_states_off_topic_mode', table_name='telegram_chat_states')
    op.drop_table('telegram_chat_states')
    # ### end Alembic commands ###
