"""add_file_processing_runs_steps

Revision ID: 504da794f2d6
Revises: 96c03e02922b
Create Date: 2026-01-22 16:30:31.895350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504da794f2d6'
down_revision: Union[str, Sequence[str], None] = '96c03e02922b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE staging_status ADD VALUE IF NOT EXISTS 'failed'")
    op.execute("ALTER TYPE staging_status ADD VALUE IF NOT EXISTS 'processing'")
    op.create_table('file_processing_runs',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column(
        'processing_type',
        postgresql.ENUM('invoice', 'price_list', 'inventory', name='processing_type', create_type=False),
        nullable=False
    ),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', 'cancelled', name='file_processing_run_status'), server_default='processing', nullable=False),
    sa.Column('pages_total', sa.Integer(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_file_processing_runs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_file_processing_runs_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_file_processing_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_runs'))
    )
    op.create_table('file_processing_steps',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', name='file_processing_step_status'), server_default='started', nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('request_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('usage_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['file_processing_runs.id'], name=op.f('fk_file_processing_steps_run_id_file_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_steps'))
    )
    op.add_column('file_processing_staging', sa.Column('run_id', sa.Uuid(), nullable=True))
    op.add_column('file_processing_staging', sa.Column('pages_total', sa.Integer(), nullable=True))
    op.add_column('file_processing_staging', sa.Column('pages_processed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('file_processing_staging', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_processing_staging', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_processing_staging', sa.Column('error_message', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_file_processing_staging_run_id_file_processing_runs'), 'file_processing_staging', 'file_processing_runs', ['run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_file_processing_staging_run_id_file_processing_runs'), 'file_processing_staging', type_='foreignkey')
    op.drop_column('file_processing_staging', 'error_message')
    op.drop_column('file_processing_staging', 'finished_at')
    op.drop_column('file_processing_staging', 'started_at')
    op.drop_column('file_processing_staging', 'pages_processed')
    op.drop_column('file_processing_staging', 'pages_total')
    op.drop_column('file_processing_staging', 'run_id')
    op.drop_table('file_processing_steps')
    op.drop_table('file_processing_runs')
    # ### end Alembic commands ###
