"""add page jobs and supplier links

Revision ID: 6eed1d0b322e
Revises: 7f0ea7c941e6
Create Date: 2026-01-26 11:14:36.090573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6eed1d0b322e'
down_revision: Union[str, Sequence[str], None] = '7f0ea7c941e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure enum types exist before use. SQLAlchemy will not create enum types
    # for op.add_column(), and CREATE TYPE has no IF NOT EXISTS in Postgres.
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'restaurant_supplier_status' AND n.nspname = 'public'
          ) THEN
            CREATE TYPE restaurant_supplier_status AS ENUM ('active', 'inactive');
          END IF;
        END $$;
        """
    )
    op.execute("ALTER TYPE restaurant_supplier_status ADD VALUE IF NOT EXISTS 'active'")
    op.execute("ALTER TYPE restaurant_supplier_status ADD VALUE IF NOT EXISTS 'inactive'")

    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'file_processing_page_status' AND n.nspname = 'public'
          ) THEN
            CREATE TYPE file_processing_page_status AS ENUM (
              'pending', 'processing', 'completed', 'failed_ocr', 'failed_extraction'
            );
          END IF;
        END $$;
        """
    )
    op.execute("ALTER TYPE file_processing_page_status ADD VALUE IF NOT EXISTS 'pending'")
    op.execute("ALTER TYPE file_processing_page_status ADD VALUE IF NOT EXISTS 'processing'")
    op.execute("ALTER TYPE file_processing_page_status ADD VALUE IF NOT EXISTS 'completed'")
    op.execute("ALTER TYPE file_processing_page_status ADD VALUE IF NOT EXISTS 'failed_ocr'")
    op.execute("ALTER TYPE file_processing_page_status ADD VALUE IF NOT EXISTS 'failed_extraction'")

    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'file_processing_source' AND n.nspname = 'public'
          ) THEN
            CREATE TYPE file_processing_source AS ENUM ('api', 'telegram');
          END IF;
        END $$;
        """
    )
    op.execute("ALTER TYPE file_processing_source ADD VALUE IF NOT EXISTS 'api'")
    op.execute("ALTER TYPE file_processing_source ADD VALUE IF NOT EXISTS 'telegram'")

    op.create_table('restaurant_suppliers',
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='restaurant_supplier_status', create_type=False), server_default='active', nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('default_currency', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_suppliers_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_restaurant_suppliers_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_suppliers')),
    sa.UniqueConstraint('restaurant_id', 'supplier_id', name='uq_restaurant_suppliers_restaurant_id_supplier_id')
    )
    op.create_index(op.f('ix_restaurant_suppliers_restaurant_id'), 'restaurant_suppliers', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_suppliers_supplier_id'), 'restaurant_suppliers', ['supplier_id'], unique=False)
    op.create_table('file_processing_page_jobs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed_ocr', 'failed_extraction', name='file_processing_page_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('ocr_retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extraction_retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['file_processing_runs.id'], name=op.f('fk_file_processing_page_jobs_run_id_file_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_page_jobs')),
    sa.UniqueConstraint('run_id', 'page_index', name='uq_file_processing_page_jobs_run_id_page_index')
    )
    op.create_index(op.f('ix_file_processing_page_jobs_page_index'), 'file_processing_page_jobs', ['page_index'], unique=False)
    op.create_index(op.f('ix_file_processing_page_jobs_run_id'), 'file_processing_page_jobs', ['run_id'], unique=False)
    op.create_table('file_processing_payloads',
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('payload_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['file_processing_runs.id'], name=op.f('fk_file_processing_payloads_run_id_file_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_payloads'))
    )
    op.create_index(op.f('ix_file_processing_payloads_page_index'), 'file_processing_payloads', ['page_index'], unique=False)
    op.create_index(op.f('ix_file_processing_payloads_run_id'), 'file_processing_payloads', ['run_id'], unique=False)
    op.create_table('supplier_item_products',
    sa.Column('supplier_item_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_item_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_supplier_item_products_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_item_id'], ['supplier_items.id'], name=op.f('fk_supplier_item_products_supplier_item_id_supplier_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_item_products')),
    sa.UniqueConstraint('supplier_item_id', 'restaurant_id', name='uq_supplier_item_products_supplier_item_id_restaurant_id')
    )
    op.create_index(op.f('ix_supplier_item_products_product_id'), 'supplier_item_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_item_products_restaurant_id'), 'supplier_item_products', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_supplier_item_products_supplier_item_id'), 'supplier_item_products', ['supplier_item_id'], unique=False)
    op.add_column('file_processing_runs', sa.Column('source', postgresql.ENUM('api', 'telegram', name='file_processing_source', create_type=False), nullable=True))
    op.add_column('file_processing_runs', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('file_processing_runs', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.add_column('file_processing_runs', sa.Column('supplier_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_file_processing_runs_session_id_telegram_sessions'), 'file_processing_runs', 'telegram_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_file_processing_runs_supplier_id_suppliers'), 'file_processing_runs', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('file_processing_staging', sa.Column('supplier_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_file_processing_staging_supplier_id_suppliers'), 'file_processing_staging', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('suppliers', sa.Column('name_normalized', sa.String(), nullable=True))
    op.create_index(op.f('ix_suppliers_name_normalized'), 'suppliers', ['name_normalized'], unique=False)
    op.drop_constraint(op.f('fk_suppliers_restaurant_id_restaurants'), 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'restaurant_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_suppliers_restaurant_id_restaurants'), 'suppliers', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_suppliers_name_normalized'), table_name='suppliers')
    op.drop_column('suppliers', 'name_normalized')
    op.drop_constraint(op.f('fk_file_processing_staging_supplier_id_suppliers'), 'file_processing_staging', type_='foreignkey')
    op.drop_column('file_processing_staging', 'supplier_id')
    op.drop_constraint(op.f('fk_file_processing_runs_supplier_id_suppliers'), 'file_processing_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_file_processing_runs_session_id_telegram_sessions'), 'file_processing_runs', type_='foreignkey')
    op.drop_column('file_processing_runs', 'supplier_id')
    op.drop_column('file_processing_runs', 'session_id')
    op.drop_column('file_processing_runs', 'chat_id')
    op.drop_column('file_processing_runs', 'source')
    op.drop_index(op.f('ix_supplier_item_products_supplier_item_id'), table_name='supplier_item_products')
    op.drop_index(op.f('ix_supplier_item_products_restaurant_id'), table_name='supplier_item_products')
    op.drop_index(op.f('ix_supplier_item_products_product_id'), table_name='supplier_item_products')
    op.drop_table('supplier_item_products')
    op.drop_index(op.f('ix_file_processing_payloads_run_id'), table_name='file_processing_payloads')
    op.drop_index(op.f('ix_file_processing_payloads_page_index'), table_name='file_processing_payloads')
    op.drop_table('file_processing_payloads')
    op.drop_index(op.f('ix_file_processing_page_jobs_run_id'), table_name='file_processing_page_jobs')
    op.drop_index(op.f('ix_file_processing_page_jobs_page_index'), table_name='file_processing_page_jobs')
    op.drop_table('file_processing_page_jobs')
    op.drop_index(op.f('ix_restaurant_suppliers_supplier_id'), table_name='restaurant_suppliers')
    op.drop_index(op.f('ix_restaurant_suppliers_restaurant_id'), table_name='restaurant_suppliers')
    op.drop_table('restaurant_suppliers')
    # ### end Alembic commands ###
