"""add ack_sent_at to telegram_sessions

Revision ID: 75dd3a76161c
Revises: a527d39bfc9e
Create Date: 2025-12-29 19:43:31.514552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dd3a76161c'
down_revision: Union[str, Sequence[str], None] = 'a527d39bfc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_sessions', sa.Column('ack_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_sessions', 'ack_sent_at')
    # ### end Alembic commands ###
