"""Add webhook_url and user_upload_limits

Revision ID: 7f0ea7c941e6
Revises: 504da794f2d6
Create Date: 2026-01-24 21:39:44.015044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ea7c941e6'
down_revision: Union[str, Sequence[str], None] = '504da794f2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_upload_limits',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('upload_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_upload_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_upload_limits')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_upload_limits_user_id'))
    )
    op.add_column('file_processing_runs', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_processing_runs', 'webhook_url')
    op.drop_table('user_upload_limits')
    # ### end Alembic commands ###
