"""add staging status awaiting fields

Revision ID: 96c03e02922b
Revises: 09988ed7ed19
Create Date: 2026-01-16 14:34:30.117340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c03e02922b'
down_revision: Union[str, Sequence[str], None] = '09988ed7ed19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE staging_status ADD VALUE IF NOT EXISTS 'awaiting_currency'")
    op.execute("ALTER TYPE staging_status ADD VALUE IF NOT EXISTS 'awaiting_supplier'")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
