"""add_supplier_contact_fields

Revision ID: a349e6609140
Revises: b2f2702842c7
Create Date: 2026-01-08 18:31:21.293187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a349e6609140'
down_revision: Union[str, Sequence[str], None] = 'b2f2702842c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contact_phone')
    op.drop_column('suppliers', 'contact_email')
    op.drop_column('suppliers', 'contact_name')
    # ### end Alembic commands ###
