"""add telegram batching tables

Revision ID: a527d39bfc9e
Revises: 3654b7cc71ad
Create Date: 2025-12-22 23:50:38.306686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a527d39bfc9e'
down_revision: Union[str, Sequence[str], None] = '3654b7cc71ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_sessions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flush_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'processing', 'closed', name='telegram_session_status'), nullable=False),
    sa.Column('hint_command', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_sessions'))
    )
    op.create_index('ix_telegram_sessions_chat_id_status', 'telegram_sessions', ['chat_id', 'status'], unique=False)
    op.create_index('ix_telegram_sessions_status_flush_at', 'telegram_sessions', ['status', 'flush_at'], unique=False)
    op.create_table('processing_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_processing_events_session_id_telegram_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_events'))
    )
    op.create_index('ix_processing_events_session_id_at', 'processing_events', ['session_id', 'at'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('file_unique_id', sa.String(), nullable=True),
    sa.Column('file_kind', sa.String(), nullable=True),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], name=op.f('fk_telegram_messages_session_id_telegram_sessions')),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('fk_telegram_messages_telegram_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_messages')),
    sa.UniqueConstraint('update_id', name=op.f('uq_telegram_messages_update_id'))
    )
    op.create_index('ix_telegram_messages_chat_id_received_at', 'telegram_messages', ['chat_id', 'received_at'], unique=False)
    op.create_index('ix_telegram_messages_file_unique_id', 'telegram_messages', ['file_unique_id'], unique=False)
    op.create_index('ix_telegram_messages_session_id', 'telegram_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_messages_session_id', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_file_unique_id', table_name='telegram_messages')
    op.drop_index('ix_telegram_messages_chat_id_received_at', table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index('ix_processing_events_session_id_at', table_name='processing_events')
    op.drop_table('processing_events')
    op.drop_index('ix_telegram_sessions_status_flush_at', table_name='telegram_sessions')
    op.drop_index('ix_telegram_sessions_chat_id_status', table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    # ### end Alembic commands ###
