"""make_supplier_items_product_id_nullable

Revision ID: eec8b182173f
Revises: a349e6609140
Create Date: 2026-01-08 19:33:17.739944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec8b182173f'
down_revision: Union[str, Sequence[str], None] = 'a349e6609140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
