"""add telegram_chat_memory

Revision ID: f08bb490ae63
Revises: 12f06baf426e
Create Date: 2026-01-05 14:30:01.023665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08bb490ae63'
down_revision: Union[str, Sequence[str], None] = '12f06baf426e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chat_memory',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_text', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_chat_memory')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_chat_memory_chat_id'))
    )
    op.create_index('ix_telegram_chat_memory_chat_id', 'telegram_chat_memory', ['chat_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_chat_memory_chat_id', table_name='telegram_chat_memory')
    op.drop_table('telegram_chat_memory')
    # ### end Alembic commands ###
